services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=gamedev
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=gamedev_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: